version: "3"
services:

  golang1.21:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang1.21
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8888:8888
      # - 443:443
    volumes:
      - .:/app
  redis:
    image: redis:6.0.3-alpine
    ports:
      - 6378:6379